plugins {
    id 'net.fabricmc.fabric-loom' version '1.18-SNAPSHOT'
}

group = 'com.bogdantokarev'
version = '1.0.0'

base { archivesName = 'BetterSprint-1.21.11-fabric' }

java {
    toolchain { languageVersion.set(JavaLanguageVersion.of(21)) }
    withSourcesJar()
}

repositories {
    maven { url = 'https://maven.fabricmc.net/' }
}

dependencies {
    minecraft "com.mojang:minecraft:1.21.11"
    implementation "net.fabricmc:fabric-loader:0.19.5"

}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') { expand 'version': project.version }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

jar {
    manifest {
        attributes(
            'Implementation-Title': 'Better Sprint',
            'Implementation-Version': project.version,
            'Implementation-Vendor': 'Bogdan_Tokarev'
        )
    }
}
