plugins {
    id 'net.fabricmc.fabric-loom' version '1.18-SNAPSHOT'
}

group = 'com.bogdantokarev'
version = '1.0.0'

base { archivesName = 'BetterSprint-26.3-fabric' }

java {
    toolchain { languageVersion.set(JavaLanguageVersion.of(25)) }
    withSourcesJar()
}

repositories {
    maven { url = 'https://maven.fabricmc.net/' }
}

dependencies {
    minecraft "com.mojang:minecraft:26.3"
    implementation "net.fabricmc:fabric-loader:0.19.5"
    implementation "net.fabricmc.fabric-api:fabric-api:0.161.0+26.3"
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') { expand 'version': project.version }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

jar {
    manifest {
        attributes(
            'Implementation-Title': 'Better Sprint',
            'Implementation-Version': project.version,
            'Implementation-Vendor': 'Bogdan_Tokarev'
        )
    }
}
