pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.minecraftforge.net' }
        maven { url = 'https://nexus.gtnewhorizons.com/repository/public/' }
        maven { url = 'https://maven.neoforged.net/releases' }
    }
}
rootProject.name = 'BetterSprint-1.12.2-forge'
