plugins {
    id 'net.minecraftforge.gradle' version '[6.0.24,6.2)'
}

group = 'com.bogdantokarev'
archivesBaseName = 'BetterSprint-1.20.1-forge'
version = '1.0.0'

java {
    toolchain { languageVersion.set(JavaLanguageVersion.of(17)) }
}

minecraft {
    mappings channel: 'official', version: '1.20.1'
    copyIdeResources = true
    runs {
        client {
            workingDirectory project.file('run')
            mods { bettersprint { source sourceSets.main } }
        }
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.3.0'
}

processResources {
    inputs.property 'version', project.version
    filesMatching('META-INF/mods.toml') { expand 'version': project.version }
}

jar {
    manifest {
        attributes(
            'Implementation-Title': 'Better Sprint',
            'Implementation-Version': project.version,
            'Implementation-Vendor': 'Bogdan_Tokarev'
        )
    }
}
afterEvaluate {
    if (tasks.findByName('reobfJar') != null) {
        jar.finalizedBy('reobfJar')
    }
}
