modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = ""

[[mods]]
modId = "bettersprint"
version = "${version}"
displayName = "Better Sprint"
authors = "Bogdan_Tokarev"
logoFile = "icon.png"
description = '''
Running now builds up momentum: +10% speed per second of sprinting up to 8.612 m/s, jump-friendly, with inertia slides, air-hit momentum keeping and camera tilt on sharp turns.
'''

[[dependencies.bettersprint]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.bettersprint]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.20.2)"
    ordering = "NONE"
    side = "CLIENT"
